//1

i1.item_id AS item_id_b1i1,i1.item_option_layout AS item_option_layout_b1i1, i1.item_stem_en AS item_stem_en_b1i1, i1.item_stem_ur AS item_stem_ur_b1i1, i1.item_option_a_en AS item_option_a_en_b1i1, i1.item_option_a_ur AS item_option_a_ur_b1i1, i1.item_option_b_en AS item_option_b_en_b1i1, i1.item_option_b_ur AS item_option_b_ur_b1i1, i1.item_option_c_en AS item_option_c_en_b1i1, i1.item_option_c_ur AS item_option_c_ur_b1i1, i1.item_option_d_en AS item_option_d_en_b1i1, i1.item_option_d_ur AS item_option_d_ur_b1i1,


i2.item_id AS item_id_b1i2,i2.item_option_layout AS item_option_layout_b1i2, i2.item_stem_en AS item_stem_en_b1i2, i2.item_stem_ur AS item_stem_ur_b1i2, i2.item_option_a_en AS item_option_a_en_b1i2, i2.item_option_a_ur AS item_option_a_ur_b1i2, i2.item_option_b_en AS item_option_b_en_b1i2, i2.item_option_b_ur AS item_option_b_ur_b1i2, i2.item_option_c_en AS item_option_c_en_b1i2, i2.item_option_c_ur AS item_option_c_ur_b1i2, i2.item_option_d_en AS item_option_d_en_b1i2, i2.item_option_d_ur AS item_option_d_ur_b1i2,


i3.item_id AS item_id_b1i3,i3.item_option_layout AS item_option_layout_b1i3, i3.item_stem_en AS item_stem_en_b1i3, i3.item_stem_ur AS item_stem_ur_b1i3, i3.item_option_a_en AS item_option_a_en_b1i3, i3.item_option_a_ur AS item_option_a_ur_b1i3, i3.item_option_b_en AS item_option_b_en_b1i3, i3.item_option_b_ur AS item_option_b_ur_b1i3, i3.item_option_c_en AS item_option_c_en_b1i3, i3.item_option_c_ur AS item_option_c_ur_b1i3, i3.item_option_d_en AS item_option_d_en_b1i3, i3.item_option_d_ur AS item_option_d_ur_b1i3,


i4.item_id AS item_id_b1i4,i4.item_option_layout AS item_option_layout_b1i4, i4.item_stem_en AS item_stem_en_b1i4, i4.item_stem_ur AS item_stem_ur_b1i4, i4.item_option_a_en AS item_option_a_en_b1i4, i4.item_option_a_ur AS item_option_a_ur_b1i4, i4.item_option_b_en AS item_option_b_en_b1i4, i4.item_option_b_ur AS item_option_b_ur_b1i4, i4.item_option_c_en AS item_option_c_en_b1i4, i4.item_option_c_ur AS item_option_c_ur_b1i4, i4.item_option_d_en AS item_option_d_en_b1i4, i4.item_option_d_ur AS item_option_d_ur_b1i4,

//2

ii1.item_id AS item_id_b2i1,ii1.item_option_layout AS item_option_layout_b2i1, ii1.item_stem_en AS item_stem_en_b2i1, ii1.item_stem_ur AS item_stem_ur_b2i1, ii1.item_option_a_en AS item_option_a_en_b2i1, ii1.item_option_a_ur AS item_option_a_ur_b2i1, ii1.item_option_b_en AS item_option_b_en_b2i1, ii1.item_option_b_ur AS item_option_b_ur_b2i1, ii1.item_option_c_en AS item_option_c_en_b2i1, ii1.item_option_c_ur AS item_option_c_ur_b2i1, ii1.item_option_d_en AS item_option_d_en_b2i1, ii1.item_option_d_ur AS item_option_d_ur_b2i1,


ii2.item_id AS item_id_b2i2,ii2.item_option_layout AS item_option_layout_b2i2, ii2.item_stem_en AS item_stem_en_b2i2, ii2.item_stem_ur AS item_stem_ur_b2i2, ii2.item_option_a_en AS item_option_a_en_b2i2, ii2.item_option_a_ur AS item_option_a_ur_b2i2, ii2.item_option_b_en AS item_option_b_en_b2i2, ii2.item_option_b_ur AS item_option_b_ur_b2i2, ii2.item_option_c_en AS item_option_c_en_b2i2, ii2.item_option_c_ur AS item_option_c_ur_b2i2, ii2.item_option_d_en AS item_option_d_en_b2i2, ii2.item_option_d_ur AS item_option_d_ur_b2i2,


ii3.item_id AS item_id_b2i3,ii3.item_option_layout AS item_option_layout_b2i3, ii3.item_stem_en AS item_stem_en_b2i3, ii3.item_stem_ur AS item_stem_ur_b2i3, ii3.item_option_a_en AS item_option_a_en_b2i3, ii3.item_option_a_ur AS item_option_a_ur_b2i3, ii3.item_option_b_en AS item_option_b_en_b2i3, ii3.item_option_b_ur AS item_option_b_ur_b2i3, ii3.item_option_c_en AS item_option_c_en_b2i3, ii3.item_option_c_ur AS item_option_c_ur_b2i3, ii3.item_option_d_en AS item_option_d_en_b2i3, ii3.item_option_d_ur AS item_option_d_ur_b2i3,


ii4.item_id AS item_id_b2i4,ii4.item_option_layout AS item_option_layout_b2i4, ii4.item_stem_en AS item_stem_en_b2i4, ii4.item_stem_ur AS item_stem_ur_b2i4, ii4.item_option_a_en AS item_option_a_en_b2i4, ii4.item_option_a_ur AS item_option_a_ur_b2i4, ii4.item_option_b_en AS item_option_b_en_b2i4, ii4.item_option_b_ur AS item_option_b_ur_b2i4, ii4.item_option_c_en AS item_option_c_en_b2i4, ii4.item_option_c_ur AS item_option_c_ur_b2i4, ii4.item_option_d_en AS item_option_d_en_b2i4, ii4.item_option_d_ur AS item_option_d_ur_b2i4,

//3


iii1.item_id AS item_id_b3i1,iii1.item_option_layout AS item_option_layout_b3i1, iii1.item_stem_en AS item_stem_en_b3i1, iii1.item_stem_ur AS item_stem_ur_b3i1, iii1.item_option_a_en AS item_option_a_en_b3i1, iii1.item_option_a_ur AS item_option_a_ur_b3i1, iii1.item_option_b_en AS item_option_b_en_b3i1, iii1.item_option_b_ur AS item_option_b_ur_b3i1, iii1.item_option_c_en AS item_option_c_en_b3i1, iii1.item_option_c_ur AS item_option_c_ur_b3i1, iii1.item_option_d_en AS item_option_d_en_b3i1, iii1.item_option_d_ur AS item_option_d_ur_b3i1,


iii2.item_id AS item_id_b3i2,iii2.item_option_layout AS item_option_layout_b3i2, iii2.item_stem_en AS item_stem_en_b3i2, iii2.item_stem_ur AS item_stem_ur_b3i2, iii2.item_option_a_en AS item_option_a_en_b3i2, iii2.item_option_a_ur AS item_option_a_ur_b3i2, iii2.item_option_b_en AS item_option_b_en_b3i2, iii2.item_option_b_ur AS item_option_b_ur_b3i2, iii2.item_option_c_en AS item_option_c_en_b3i2, iii2.item_option_c_ur AS item_option_c_ur_b3i2, iii2.item_option_d_en AS item_option_d_en_b3i2, iii2.item_option_d_ur AS item_option_d_ur_b3i2,


iii3.item_id AS item_id_b3i3,iii3.item_option_layout AS item_option_layout_b3i3, iii3.item_stem_en AS item_stem_en_b3i3, iii3.item_stem_ur AS item_stem_ur_b3i3, iii3.item_option_a_en AS item_option_a_en_b3i3, iii3.item_option_a_ur AS item_option_a_ur_b3i3, iii3.item_option_b_en AS item_option_b_en_b3i3, iii3.item_option_b_ur AS item_option_b_ur_b3i3, iii3.item_option_c_en AS item_option_c_en_b3i3, iii3.item_option_c_ur AS item_option_c_ur_b3i3, iii3.item_option_d_en AS item_option_d_en_b3i3, iii3.item_option_d_ur AS item_option_d_ur_b3i3,

i4.item_id AS item_id_b3i4,iii4.item_option_layout AS item_option_layout_b3i4, iii4.item_stem_en AS item_stem_en_b3i4, iii4.item_stem_ur AS item_stem_ur_b3i4, iii4.item_option_a_en AS item_option_a_en_b3i4, iii4.item_option_a_ur AS item_option_a_ur_b3i4, iii4.item_option_b_en AS item_option_b_en_b3i4, iii4.item_option_b_ur AS item_option_b_ur_b3i4, iii4.item_option_c_en AS item_option_c_en_b3i4, iii4.item_option_c_ur AS item_option_c_ur_b3i4, iii4.item_option_d_en AS item_option_d_en_b3i4, iii4.item_option_d_ur AS item_option_d_ur_b3i4,

//4

iv1.item_id AS item_id_b4i1,iv1.item_option_layout AS item_option_layout_b4i1, iv1.item_stem_en AS item_stem_en_b4i1, iv1.item_stem_ur AS item_stem_ur_b4i1, iv1.item_option_a_en AS item_option_a_en_b4i1, iv1.item_option_a_ur AS item_option_a_ur_b4i1, iv1.item_option_b_en AS item_option_b_en_b4i1, iv1.item_option_b_ur AS item_option_b_ur_b4i1, iv1.item_option_c_en AS item_option_c_en_b4i1, iv1.item_option_c_ur AS item_option_c_ur_b4i1, iv1.item_option_d_en AS item_option_d_en_b4i1, iv1.item_option_d_ur AS item_option_d_ur_b4i1,


iv2.item_id AS item_id_b4i2,iv2.item_option_layout AS item_option_layout_b4i2, iv2.item_stem_en AS item_stem_en_b4i2, iv2.item_stem_ur AS item_stem_ur_b4i2, iv2.item_option_a_en AS item_option_a_en_b4i2, iv2.item_option_a_ur AS item_option_a_ur_b4i2, iv2.item_option_b_en AS item_option_b_en_b4i2, iv2.item_option_b_ur AS item_option_b_ur_b4i2, iv2.item_option_c_en AS item_option_c_en_b4i2, iv2.item_option_c_ur AS item_option_c_ur_b4i2, iv2.item_option_d_en AS item_option_d_en_b4i2, iv2.item_option_d_ur AS item_option_d_ur_b4i2,


iv3.item_id AS item_id_b4i3,iv3.item_option_layout AS item_option_layout_b4i3, iv3.item_stem_en AS item_stem_en_b4i3, iv3.item_stem_ur AS item_stem_ur_b4i3, iv3.item_option_a_en AS item_option_a_en_b4i3, iv3.item_option_a_ur AS item_option_a_ur_b4i3, iv3.item_option_b_en AS item_option_b_en_b4i3, iv3.item_option_b_ur AS item_option_b_ur_b4i3, iv3.item_option_c_en AS item_option_c_en_b4i3, iv3.item_option_c_ur AS item_option_c_ur_b4i3, iv3.item_option_d_en AS item_option_d_en_b4i3, iv3.item_option_d_ur AS item_option_d_ur_b4i3,


iv4.item_id AS item_id_b4i4,iv4.item_option_layout AS item_option_layout_b4i4, iv4.item_stem_en AS item_stem_en_b4i4, iv4.item_stem_ur AS item_stem_ur_b4i4, iv4.item_option_a_en AS item_option_a_en_b4i4, iv4.item_option_a_ur AS item_option_a_ur_b4i4, iv4.item_option_b_en AS item_option_b_en_b4i4, iv4.item_option_b_ur AS item_option_b_ur_b4i4, iv4.item_option_c_en AS item_option_c_en_b4i4, iv4.item_option_c_ur AS item_option_c_ur_b4i4, iv4.item_option_d_en AS item_option_d_en_b4i4, iv4.item_option_d_ur AS item_option_d_ur_b4i4

=============================
//5

v1.item_id AS item_id_b5i1,v1.item_option_layout AS item_option_layout_b5i1, v1.item_stem_en AS item_stem_en_b5i1, v1.item_stem_ur AS item_stem_ur_b5i1, v1.item_option_a_en AS item_option_a_en_b5i1, v1.item_option_a_ur AS item_option_a_ur_b5i1, v1.item_option_b_en AS item_option_b_en_b5i1, v1.item_option_b_ur AS item_option_b_ur_b5i1, v1.item_option_c_en AS item_option_c_en_b5i1, v1.item_option_c_ur AS item_option_c_ur_b5i1, v1.item_option_d_en AS item_option_d_en_b5i1, v1.item_option_d_ur AS item_option_d_ur_b5i1,


v2.item_id AS item_id_b5i2,v2.item_option_layout AS item_option_layout_b5i2, v2.item_stem_en AS item_stem_en_b5i2, v2.item_stem_ur AS item_stem_ur_b5i2, v2.item_option_a_en AS item_option_a_en_b5i2, v2.item_option_a_ur AS item_option_a_ur_b5i2, v2.item_option_b_en AS item_option_b_en_b5i2, v2.item_option_b_ur AS item_option_b_ur_b5i2, v2.item_option_c_en AS item_option_c_en_b5i2, v2.item_option_c_ur AS item_option_c_ur_b5i2, v2.item_option_d_en AS item_option_d_en_b5i2, v2.item_option_d_ur AS item_option_d_ur_b5i2,


v3.item_id AS item_id_b5i3,v3.item_option_layout AS item_option_layout_b5i3, v3.item_stem_en AS item_stem_en_b5i3, v3.item_stem_ur AS item_stem_ur_b5i3, v3.item_option_a_en AS item_option_a_en_b5i3, v3.item_option_a_ur AS item_option_a_ur_b5i3, v3.item_option_b_en AS item_option_b_en_b5i3, v3.item_option_b_ur AS item_option_b_ur_b5i3, v3.item_option_c_en AS item_option_c_en_b5i3, v3.item_option_c_ur AS item_option_c_ur_b5i3, v3.item_option_d_en AS item_option_d_en_b5i3, i3.item_option_d_ur AS item_option_d_ur_b5i3,


v4.item_id AS item_id_b5i4,v4.item_option_layout AS item_option_layout_b5i4, v4.item_stem_en AS item_stem_en_b5i4, v4.item_stem_ur AS item_stem_ur_b5i4, v4.item_option_a_en AS item_option_a_en_b5i4, v4.item_option_a_ur AS item_option_a_ur_b5i4, v4.item_option_b_en AS item_option_b_en_b5i4, v4.item_option_b_ur AS item_option_b_ur_b5i4, v4.item_option_c_en AS item_option_c_en_b5i4, v4.item_option_c_ur AS item_option_c_ur_b5i4, v4.item_option_d_en AS item_option_d_en_b5i4, v4.item_option_d_ur AS item_option_d_ur_b5i4,

//6

vi1.item_id AS item_id_b6i1,vi1.item_option_layout AS item_option_layout_b6i1, vi1.item_stem_en AS item_stem_en_b6i1, vi1.item_stem_ur AS item_stem_ur_b6i1, vi1.item_option_a_en AS item_option_a_en_b6i1, vi1.item_option_a_ur AS item_option_a_ur_b6i1, vi1.item_option_b_en AS item_option_b_en_b6i1, vi1.item_option_b_ur AS item_option_b_ur_b6i1, vi1.item_option_c_en AS item_option_c_en_b6i1, vi1.item_option_c_ur AS item_option_c_ur_b6i1, vi1.item_option_d_en AS item_option_d_en_b6i1, vi1.item_option_d_ur AS item_option_d_ur_b6i1,


vi2.item_id AS item_id_b6i2,vi2.item_option_layout AS item_option_layout_b6i2, vi2.item_stem_en AS item_stem_en_b6i2, vi2.item_stem_ur AS item_stem_ur_b6i2, vi2.item_option_a_en AS item_option_a_en_b6i2, vi2.item_option_a_ur AS item_option_a_ur_b6i2, vi2.item_option_b_en AS item_option_b_en_b6i2, vi2.item_option_b_ur AS item_option_b_ur_b6i2, vi2.item_option_c_en AS item_option_c_en_b6i2, vi2.item_option_c_ur AS item_option_c_ur_b6i2, vi2.item_option_d_en AS item_option_d_en_b6i2, vi2.item_option_d_ur AS item_option_d_ur_b6i2,


vi3.item_id AS item_id_b6i3,vi3.item_option_layout AS item_option_layout_b6i3, vi3.item_stem_en AS item_stem_en_b6i3, vi3.item_stem_ur AS item_stem_ur_b6i3, vi3.item_option_a_en AS item_option_a_en_b6i3, vi3.item_option_a_ur AS item_option_a_ur_b6i3, vi3.item_option_b_en AS item_option_b_en_b6i3, vi3.item_option_b_ur AS item_option_b_ur_b6i3, vi3.item_option_c_en AS item_option_c_en_b6i3, vi3.item_option_c_ur AS item_option_c_ur_b6i3, vi3.item_option_d_en AS item_option_d_en_b6i3, vi3.item_option_d_ur AS item_option_d_ur_b6i3,


vi4.item_id AS item_id_b6i4,vi4.item_option_layout AS item_option_layout_b6i4, vi4.item_stem_en AS item_stem_en_b6i4, vi4.item_stem_ur AS item_stem_ur_b6i4, vi4.item_option_a_en AS item_option_a_en_b6i4, vi4.item_option_a_ur AS item_option_a_ur_b6i4, vi4.item_option_b_en AS item_option_b_en_b6i4, vi4.item_option_b_ur AS item_option_b_ur_b6i4, vi4.item_option_c_en AS item_option_c_en_b6i4, vi4.item_option_c_ur AS item_option_c_ur_b6i4, vi4.item_option_d_en AS item_option_d_en_b6i4, vi4.item_option_d_ur AS item_option_d_ur_b6i4,

//7

vii1.item_id AS item_id_b7i1,vii1.item_option_layout AS item_option_layout_b7i1, vii1.item_stem_en AS item_stem_en_b7i1, vii1.item_stem_ur AS item_stem_ur_b7i1, vii1.item_option_a_en AS item_option_a_en_b7i1, vii1.item_option_a_ur AS item_option_a_ur_b7i1, vii1.item_option_b_en AS item_option_b_en_b7i1, vii1.item_option_b_ur AS item_option_b_ur_b7i1, vii1.item_option_c_en AS item_option_c_en_b7i1, vii1.item_option_c_ur AS item_option_c_ur_b7i1, vii1.item_option_d_en AS item_option_d_en_b7i1, vii1.item_option_d_ur AS item_option_d_ur_b7i1,


vii2.item_id AS item_id_b7i2,vii2.item_option_layout AS item_option_layout_b7i2, vii2.item_stem_en AS item_stem_en_b7i2, vii2.item_stem_ur AS item_stem_ur_b7i2, vii2.item_option_a_en AS item_option_a_en_b7i2, vii2.item_option_a_ur AS item_option_a_ur_b7i2, vii2.item_option_b_en AS item_option_b_en_b7i2, vii2.item_option_b_ur AS item_option_b_ur_b7i2, vii2.item_option_c_en AS item_option_c_en_b7i2, vii2.item_option_c_ur AS item_option_c_ur_b7i2, vii2.item_option_d_en AS item_option_d_en_b7i2, vii2.item_option_d_ur AS item_option_d_ur_b7i2,


vii3.item_id AS item_id_b7i3,vii3.item_option_layout AS item_option_layout_b7i3, vii3.item_stem_en AS item_stem_en_b7i3, vii3.item_stem_ur AS item_stem_ur_b7i3, vii3.item_option_a_en AS item_option_a_en_b7i3, vii3.item_option_a_ur AS item_option_a_ur_b7i3, vii3.item_option_b_en AS item_option_b_en_b7i3, vii3.item_option_b_ur AS item_option_b_ur_b7i3, vii3.item_option_c_en AS item_option_c_en_b7i3, vii3.item_option_c_ur AS item_option_c_ur_b7i3, vii3.item_option_d_en AS item_option_d_en_b7i3, vii3.item_option_d_ur AS item_option_d_ur_b7i3,

vii4.item_id AS item_id_b7i4,vii4.item_option_layout AS item_option_layout_b7i4, vii4.item_stem_en AS item_stem_en_b7i4, vii4.item_stem_ur AS item_stem_ur_b7i4, vii4.item_option_a_en AS item_option_a_en_b7i4, vii4.item_option_a_ur AS item_option_a_ur_b7i4, vii4.item_option_b_en AS item_option_b_en_b7i4, vii4.item_option_b_ur AS item_option_b_ur_b7i4, vii4.item_option_c_en AS item_option_c_en_b7i4, vii4.item_option_c_ur AS item_option_c_ur_b7i4, vii4.item_option_d_en AS item_option_d_en_b7i4, vii4.item_option_d_ur AS item_option_d_ur_b7i4,

//8

viii1.item_id AS item_id_b8i1,viii1.item_option_layout AS item_option_layout_b8i1, viii1.item_stem_en AS item_stem_en_b8i1, viii1.item_stem_ur AS item_stem_ur_b8i1, viii1.item_option_a_en AS item_option_a_en_b8i1, viii1.item_option_a_ur AS item_option_a_ur_b8i1, viii1.item_option_b_en AS item_option_b_en_b8i1, viii1.item_option_b_ur AS item_option_b_ur_b8i1, viii1.item_option_c_en AS item_option_c_en_b8i1, viii1.item_option_c_ur AS item_option_c_ur_b8i1, viii1.item_option_d_en AS item_option_d_en_b8i1, viii1.item_option_d_ur AS item_option_d_ur_b8i1,

viii2.item_id AS item_id_b8i2,viii2.item_option_layout AS item_option_layout_b8i2, viii2.item_stem_en AS item_stem_en_b8i2, viii2.item_stem_ur AS item_stem_ur_b8i2, viii2.item_option_a_en AS item_option_a_en_b8i2, viii2.item_option_a_ur AS item_option_a_ur_b8i2, viii2.item_option_b_en AS item_option_b_en_b8i2, viii2.item_option_b_ur AS item_option_b_ur_b8i2, viii2.item_option_c_en AS item_option_c_en_b8i2, viii2.item_option_c_ur AS item_option_c_ur_b8i2, viii2.item_option_d_en AS item_option_d_en_b8i2, viii2.item_option_d_ur AS item_option_d_ur_b8i2,

vii3.item_id AS item_id_b8i3,vii3.item_option_layout AS item_option_layout_b8i3, vii3.item_stem_en AS item_stem_en_b8i3, vii3.item_stem_ur AS item_stem_ur_b8i3, vii3.item_option_a_en AS item_option_a_en_b8i3, vii3.item_option_a_ur AS item_option_a_ur_b8i3, vii3.item_option_b_en AS item_option_b_en_b8i3, vii3.item_option_b_ur AS item_option_b_ur_b8i3, vii3.item_option_c_en AS item_option_c_en_b8i3, vii3.item_option_c_ur AS item_option_c_ur_b8i3, vii3.item_option_d_en AS item_option_d_en_b8i3, vii3.item_option_d_ur AS item_option_d_ur_b8i3,

vii4.item_id AS item_id_b8i4,vii4.item_option_layout AS item_option_layout_b8i4, vii4.item_stem_en AS item_stem_en_b8i4, vii4.item_stem_ur AS item_stem_ur_b8i4, vii4.item_option_a_en AS item_option_a_en_b8i4, vii4.item_option_a_ur AS item_option_a_ur_b8i4, vii4.item_option_b_en AS item_option_b_en_b8i4, vii4.item_option_b_ur AS item_option_b_ur_b8i4, vii4.item_option_c_en AS item_option_c_en_b8i4, vii4.item_option_c_ur AS item_option_c_ur_b8i4, vii4.item_option_d_en AS item_option_d_en_b8i4, vii4.item_option_d_ur AS item_option_d_ur_b8i4

====================================================================================
//9
ix1.item_id AS item_id_b9i1,ix1.item_option_layout AS item_option_layout_b9i1, ix1.item_stem_en AS item_stem_en_b9i1, ix1.item_stem_ur AS item_stem_ur_b9i1, ix1.item_option_a_en AS item_option_a_en_b9i1, ix1.item_option_a_ur AS item_option_a_ur_b9i1, ix1.item_option_b_en AS item_option_b_en_b9i1, ix1.item_option_b_ur AS item_option_b_ur_b9i1, ix1.item_option_c_en AS item_option_c_en_b9i1, ix1.item_option_c_ur AS item_option_c_ur_b9i1, ix1.item_option_d_en AS item_option_d_en_b9i1, ix1.item_option_d_ur AS item_option_d_ur_b9i1, ix2.item_id AS item_id_b9i2,ix2.item_option_layout AS item_option_layout_b9i2, ix2.item_stem_en AS item_stem_en_b9i2, ix2.item_stem_ur AS item_stem_ur_b9i2, ix2.item_option_a_en AS item_option_a_en_b9i2, ix2.item_option_a_ur AS item_option_a_ur_b9i2, ix2.item_option_b_en AS item_option_b_en_b9i2, ix2.item_option_b_ur AS item_option_b_ur_b9i2, ix2.item_option_c_en AS item_option_c_en_b9i2, ix2.item_option_c_ur AS item_option_c_ur_b9i2, ix2.item_option_d_en AS item_option_d_en_b9i2, ix2.item_option_d_ur AS item_option_d_ur_b9i2, ix3.item_id AS item_id_b9i3,ix3.item_option_layout AS item_option_layout_b9i3, ix3.item_stem_en AS item_stem_en_b9i3, ix3.item_stem_ur AS item_stem_ur_b9i3, ix3.item_option_a_en AS item_option_a_en_b9i3, ix3.item_option_a_ur AS item_option_a_ur_b9i3, ix3.item_option_b_en AS item_option_b_en_b9i3, ix3.item_option_b_ur AS item_option_b_ur_b9i3, ix3.item_option_c_en AS item_option_c_en_b9i3, ix3.item_option_c_ur AS item_option_c_ur_b9i3, ix3.item_option_d_en AS item_option_d_en_b9i3, ix3.item_option_d_ur AS item_option_d_ur_b9i3, ix4.item_id AS item_id_b9i4,ix4.item_option_layout AS item_option_layout_b9i4, ix4.item_stem_en AS item_stem_en_b9i4, ix4.item_stem_ur AS item_stem_ur_b9i4, ix4.item_option_a_en AS item_option_a_en_b9i4, ix4.item_option_a_ur AS item_option_a_ur_b9i4, ix4.item_option_b_en AS item_option_b_en_b9i4, ix4.item_option_b_ur AS item_option_b_ur_b9i4, ix4.item_option_c_en AS item_option_c_en_b9i4, ix4.item_option_c_ur AS item_option_c_ur_b9i4, ix4.item_option_d_en AS item_option_d_en_b9i4, ix4.item_option_d_ur AS item_option_d_ur_b9i4,
//10
x1.item_id AS item_id_b10i1,x1.item_option_layout AS item_option_layout_b10i1, x1.item_stem_en AS item_stem_en_b10i1, x1.item_stem_ur AS item_stem_ur_b10i1, x1.item_option_a_en AS item_option_a_en_b10i1, x1.item_option_a_ur AS item_option_a_ur_b10i1, x1.item_option_b_en AS item_option_b_en_b10i1, x1.item_option_b_ur AS item_option_b_ur_b10i1, x1.item_option_c_en AS item_option_c_en_b10i1, x1.item_option_c_ur AS item_option_c_ur_b10i1, x1.item_option_d_en AS item_option_d_en_b10i1, x1.item_option_d_ur AS item_option_d_ur_b10i1, x2.item_id AS item_id_b10i2,x2.item_option_layout AS item_option_layout_b10i2, x2.item_stem_en AS item_stem_en_b10i2, x2.item_stem_ur AS item_stem_ur_b10i2, x2.item_option_a_en AS item_option_a_en_b10i2, x2.item_option_a_ur AS item_option_a_ur_b10i2, x2.item_option_b_en AS item_option_b_en_b10i2, x2.item_option_b_ur AS item_option_b_ur_b10i2, x2.item_option_c_en AS item_option_c_en_b10i2, x2.item_option_c_ur AS item_option_c_ur_b10i2, x2.item_option_d_en AS item_option_d_en_b10i2, x2.item_option_d_ur AS item_option_d_ur_b10i2, x3.item_id AS item_id_b10i3,x3.item_option_layout AS item_option_layout_b10i3, x3.item_stem_en AS item_stem_en_b10i3, x3.item_stem_ur AS item_stem_ur_b10i3, x3.item_option_a_en AS item_option_a_en_b10i3, x3.item_option_a_ur AS item_option_a_ur_b10i3, x3.item_option_b_en AS item_option_b_en_b10i3, x3.item_option_b_ur AS item_option_b_ur_b10i3, x3.item_option_c_en AS item_option_c_en_b10i3, x3.item_option_c_ur AS item_option_c_ur_b10i3, x3.item_option_d_en AS item_option_d_en_b10i3, x3.item_option_d_ur AS item_option_d_ur_b10i3,
x4.item_id AS item_id_b10i4,x4.item_option_layout AS item_option_layout_b10i4, x4.item_stem_en AS item_stem_en_b10i4, x4.item_stem_ur AS item_stem_ur_b10i4, x4.item_option_a_en AS item_option_a_en_b10i4, x4.item_option_a_ur AS item_option_a_ur_b10i4, x4.item_option_b_en AS item_option_b_en_b10i4, x4.item_option_b_ur AS item_option_b_ur_b10i4, x4.item_option_c_en AS item_option_c_en_b10i4, x4.item_option_c_ur AS item_option_c_ur_b10i4, x4.item_option_d_en AS item_option_d_en_b10i4, x4.item_option_d_ur AS item_option_d_ur_b10i4, 
//11
xi1.item_id AS item_id_b11i1,xi1.item_option_layout AS item_option_layout_b11i1, xi1.item_stem_en AS item_stem_en_b11i1, xi1.item_stem_ur AS item_stem_ur_b11i1, xi1.item_option_a_en AS item_option_a_en_b11i1, xi1.item_option_a_ur AS item_option_a_ur_b11i1, xi1.item_option_b_en AS item_option_b_en_b11i1, xi1.item_option_b_ur AS item_option_b_ur_b11i1, xi1.item_option_c_en AS item_option_c_en_b11i1, xi1.item_option_c_ur AS item_option_c_ur_b11i1, xi1.item_option_d_en AS item_option_d_en_b11i1, xi1.item_option_d_ur AS item_option_d_ur_b11i1, xi2.item_id AS item_id_b11i2,xi2.item_option_layout AS item_option_layout_b11i2, xi2.item_stem_en AS item_stem_en_b11i2, xi2.item_stem_ur AS item_stem_ur_b11i2, xi2.item_option_a_en AS item_option_a_en_b11i2, xi2.item_option_a_ur AS item_option_a_ur_b11i2, xi2.item_option_b_en AS item_option_b_en_b11i2, xi2.item_option_b_ur AS item_option_b_ur_b11i2, xi2.item_option_c_en AS item_option_c_en_b11i2, xi2.item_option_c_ur AS item_option_c_ur_b11i2, xi2.item_option_d_en AS item_option_d_en_b11i2, xi2.item_option_d_ur AS item_option_d_ur_b11i2, xi3.item_id AS item_id_b11i3,xi3.item_option_layout AS item_option_layout_b11i3, xi3.item_stem_en AS item_stem_en_b11i3, xi3.item_stem_ur AS item_stem_ur_b11i3, xi3.item_option_a_en AS item_option_a_en_b11i3, xi3.item_option_a_ur AS item_option_a_ur_b11i3, xi3.item_option_b_en AS item_option_b_en_b11i3, xi3.item_option_b_ur AS item_option_b_ur_b11i3, xi3.item_option_c_en AS item_option_c_en_b11i3, xi3.item_option_c_ur AS item_option_c_ur_b11i3, xi3.item_option_d_en AS item_option_d_en_b11i3, xi3.item_option_d_ur AS item_option_d_ur_b11i3, i4.item_id AS item_id_b11i4,xi4.item_option_layout AS item_option_layout_b11i4, xi4.item_stem_en AS item_stem_en_b11i4, xi4.item_stem_ur AS item_stem_ur_b11i4, xi4.item_option_a_en AS item_option_a_en_b11i4, xi4.item_option_a_ur AS item_option_a_ur_b11i4, xi4.item_option_b_en AS item_option_b_en_b11i4, xi4.item_option_b_ur AS item_option_b_ur_b11i4, xi4.item_option_c_en AS item_option_c_en_b11i4, xi4.item_option_c_ur AS item_option_c_ur_b11i4, xi4.item_option_d_en AS item_option_d_en_b11i4, xi4.item_option_d_ur AS item_option_d_ur_b11i4,
//12
xii1.item_id AS item_id_b12i1,xii1.item_option_layout AS item_option_layout_b12i1, xii1.item_stem_en AS item_stem_en_b12i1, xii1.item_stem_ur AS item_stem_ur_b12i1, xii1.item_option_a_en AS item_option_a_en_b12i1, xii1.item_option_a_ur AS item_option_a_ur_b12i1, xii1.item_option_b_en AS item_option_b_en_b12i1, xii1.item_option_b_ur AS item_option_b_ur_b12i1, xii1.item_option_c_en AS item_option_c_en_b12i1, xii1.item_option_c_ur AS item_option_c_ur_b12i1, xii1.item_option_d_en AS item_option_d_en_b12i1, xii1.item_option_d_ur AS item_option_d_ur_b12i1, xii2.item_id AS item_id_b12i2,xii2.item_option_layout AS item_option_layout_b12i2, xii2.item_stem_en AS item_stem_en_b12i2, xii2.item_stem_ur AS item_stem_ur_b12i2, xii2.item_option_a_en AS item_option_a_en_b12i2, xii2.item_option_a_ur AS item_option_a_ur_b12i2, xii2.item_option_b_en AS item_option_b_en_b12i2, xii2.item_option_b_ur AS item_option_b_ur_b12i2, xii2.item_option_c_en AS item_option_c_en_b12i2, xii2.item_option_c_ur AS item_option_c_ur_b12i2, xii2.item_option_d_en AS item_option_d_en_b12i2, xii2.item_option_d_ur AS item_option_d_ur_b12i2, xii3.item_id AS item_id_b12i3,xii3.item_option_layout AS item_option_layout_b12i3, xii3.item_stem_en AS item_stem_en_b12i3, xii3.item_stem_ur AS item_stem_ur_b12i3, xii3.item_option_a_en AS item_option_a_en_b12i3, xii3.item_option_a_ur AS item_option_a_ur_b12i3, xii3.item_option_b_en AS item_option_b_en_b12i3, xii3.item_option_b_ur AS item_option_b_ur_b12i3, xii3.item_option_c_en AS item_option_c_en_b12i3, xii3.item_option_c_ur AS item_option_c_ur_b12i3, xii3.item_option_d_en AS item_option_d_en_b12i3, xii3.item_option_d_ur AS item_option_d_ur_b12i3,
xii4.item_id AS item_id_b12i4,xii4.item_option_layout AS item_option_layout_b12i4, xii4.item_stem_en AS item_stem_en_b12i4, xii4.item_stem_ur AS item_stem_ur_b12i4, xii4.item_option_a_en AS item_option_a_en_b12i4, xii4.item_option_a_ur AS item_option_a_ur_b12i4, xii4.item_option_b_en AS item_option_b_en_b12i4, xii4.item_option_b_ur AS item_option_b_ur_b12i4, xii4.item_option_c_en AS item_option_c_en_b12i4, xii4.item_option_c_ur AS item_option_c_ur_b12i4, xii4.item_option_d_en AS item_option_d_en_b12i4, xii4.item_option_d_ur AS item_option_d_ur_b12i4
=============================

====================================================================================
//13
xiii1.item_id AS item_id_b13i1,xiii1.item_option_layout AS item_option_layout_b13i1, xiii1.item_stem_en AS item_stem_en_b13i1, xiii1.item_stem_ur AS item_stem_ur_b13i1, xiii1.item_option_a_en AS item_option_a_en_b13i1, xiii1.item_option_a_ur AS item_option_a_ur_b13i1, xiii1.item_option_b_en AS item_option_b_en_b13i1, xiii1.item_option_b_ur AS item_option_b_ur_b13i1, xiii1.item_option_c_en AS item_option_c_en_b13i1, xiii1.item_option_c_ur AS item_option_c_ur_b13i1, xiii1.item_option_d_en AS item_option_d_en_b13i1, xiii1.item_option_d_ur AS item_option_d_ur_b13i1, xiii2.item_id AS item_id_b13i2,xiii2.item_option_layout AS item_option_layout_b13i2, xiii2.item_stem_en AS item_stem_en_b13i2, xiii2.item_stem_ur AS item_stem_ur_b13i2, xiii2.item_option_a_en AS item_option_a_en_b13i2, xiii2.item_option_a_ur AS item_option_a_ur_b13i2, xiii2.item_option_b_en AS item_option_b_en_b13i2, xiii2.item_option_b_ur AS item_option_b_ur_b13i2, xiii2.item_option_c_en AS item_option_c_en_b13i2, xiii2.item_option_c_ur AS item_option_c_ur_b13i2, xiii2.item_option_d_en AS item_option_d_en_b13i2, xiii2.item_option_d_ur AS item_option_d_ur_b13i2, xiii3.item_id AS item_id_b13i3,xiii3.item_option_layout AS item_option_layout_b13i3, xiii3.item_stem_en AS item_stem_en_b13i3, xiii3.item_stem_ur AS item_stem_ur_b13i3, xiii3.item_option_a_en AS item_option_a_en_b13i3, xiii3.item_option_a_ur AS item_option_a_ur_b13i3, xiii3.item_option_b_en AS item_option_b_en_b13i3, xiii3.item_option_b_ur AS item_option_b_ur_b13i3, xiii3.item_option_c_en AS item_option_c_en_b13i3, xiii3.item_option_c_ur AS item_option_c_ur_b13i3, xiii3.item_option_d_en AS item_option_d_en_b13i3, xiii3.item_option_d_ur AS item_option_d_ur_b13i3, xiii4.item_id AS item_id_b13i4,xiii4.item_option_layout AS item_option_layout_b13i4, xiii4.item_stem_en AS item_stem_en_b13i4, xiii4.item_stem_ur AS item_stem_ur_b13i4, xiii4.item_option_a_en AS item_option_a_en_b13i4, xiii4.item_option_a_ur AS item_option_a_ur_b13i4, xiii4.item_option_b_en AS item_option_b_en_b13i4, xiii4.item_option_b_ur AS item_option_b_ur_b13i4, xiii4.item_option_c_en AS item_option_c_en_b13i4, xiii4.item_option_c_ur AS item_option_c_ur_b13i4, xiii4.item_option_d_en AS item_option_d_en_b13i4, xiii4.item_option_d_ur AS item_option_d_ur_b13i4,
//14
xiv1.item_id AS item_id_b14i1,xiv1.item_option_layout AS item_option_layout_b14i1, xiv1.item_stem_en AS item_stem_en_b14i1, xiv1.item_stem_ur AS item_stem_ur_b14i1, xiv1.item_option_a_en AS item_option_a_en_b14i1, xiv1.item_option_a_ur AS item_option_a_ur_b14i1, xiv1.item_option_b_en AS item_option_b_en_b14i1, xiv1.item_option_b_ur AS item_option_b_ur_b14i1, xiv1.item_option_c_en AS item_option_c_en_b14i1, xiv1.item_option_c_ur AS item_option_c_ur_b14i1, xiv1.item_option_d_en AS item_option_d_en_b14i1, xiv1.item_option_d_ur AS item_option_d_ur_b14i1, xiv2.item_id AS item_id_b14i2,xiv2.item_option_layout AS item_option_layout_b14i2, xiv2.item_stem_en AS item_stem_en_b14i2, xiv2.item_stem_ur AS item_stem_ur_b14i2, xiv2.item_option_a_en AS item_option_a_en_b14i2, xiv2.item_option_a_ur AS item_option_a_ur_b14i2, xiv2.item_option_b_en AS item_option_b_en_b14i2, xiv2.item_option_b_ur AS item_option_b_ur_b14i2, xiv2.item_option_c_en AS item_option_c_en_b14i2, xiv2.item_option_c_ur AS item_option_c_ur_b14i2, xiv2.item_option_d_en AS item_option_d_en_b14i2, xiv2.item_option_d_ur AS item_option_d_ur_b14i2, xiv3.item_id AS item_id_b14i3,xiv3.item_option_layout AS item_option_layout_b14i3, xiv3.item_stem_en AS item_stem_en_b14i3, xiv3.item_stem_ur AS item_stem_ur_b14i3, xiv3.item_option_a_en AS item_option_a_en_b14i3, xiv3.item_option_a_ur AS item_option_a_ur_b14i3, xiv3.item_option_b_en AS item_option_b_en_b14i3, xiv3.item_option_b_ur AS item_option_b_ur_b14i3, xiv3.item_option_c_en AS item_option_c_en_b14i3, xiv3.item_option_c_ur AS item_option_c_ur_b14i3, xiv3.item_option_d_en AS item_option_d_en_b14i3, xiv3.item_option_d_ur AS item_option_d_ur_b14i3, xiv4.item_id AS item_id_b14i4,xiv4.item_option_layout AS item_option_layout_b14i4, xiv4.item_stem_en AS item_stem_en_b14i4, xiv4.item_stem_ur AS item_stem_ur_b14i4, xiv4.item_option_a_en AS item_option_a_en_b14i4, xiv4.item_option_a_ur AS item_option_a_ur_b14i4, xiv4.item_option_b_en AS item_option_b_en_b14i4, xiv4.item_option_b_ur AS item_option_b_ur_b14i4, xiv4.item_option_c_en AS item_option_c_en_b14i4, xiv4.item_option_c_ur AS item_option_c_ur_b14i4, xiv4.item_option_d_en AS item_option_d_en_b14i4, xiv4.item_option_d_ur AS item_option_d_ur_b14i4, 
//15
xv1.item_id AS item_id_b15i1,xv1.item_option_layout AS item_option_layout_b15i1, xv1.item_stem_en AS item_stem_en_b15i1, xv1.item_stem_ur AS item_stem_ur_b15i1, xv1.item_option_a_en AS item_option_a_en_b15i1, xv1.item_option_a_ur AS item_option_a_ur_b15i1, xv1.item_option_b_en AS item_option_b_en_b15i1, xv1.item_option_b_ur AS item_option_b_ur_b15i1, xv1.item_option_c_en AS item_option_c_en_b15i1, xv1.item_option_c_ur AS item_option_c_ur_b15i1, xv1.item_option_d_en AS item_option_d_en_b15i1, xv1.item_option_d_ur AS item_option_d_ur_b15i1, xv2.item_id AS item_id_b15i2,xv2.item_option_layout AS item_option_layout_b15i2, xv2.item_stem_en AS item_stem_en_b15i2, xv2.item_stem_ur AS item_stem_ur_b15i2, xv2.item_option_a_en AS item_option_a_en_b15i2, xv2.item_option_a_ur AS item_option_a_ur_b15i2, xv2.item_option_b_en AS item_option_b_en_b15i2, xv2.item_option_b_ur AS item_option_b_ur_b15i2, xv2.item_option_c_en AS item_option_c_en_b15i2, xv2.item_option_c_ur AS item_option_c_ur_b15i2, xv2.item_option_d_en AS item_option_d_en_b15i2, xv2.item_option_d_ur AS item_option_d_ur_b15i2, xv3.item_id AS item_id_b15i3,xv3.item_option_layout AS item_option_layout_b15i3, xv3.item_stem_en AS item_stem_en_b15i3, xv3.item_stem_ur AS item_stem_ur_b15i3, xv3.item_option_a_en AS item_option_a_en_b15i3, xv3.item_option_a_ur AS item_option_a_ur_b15i3, xv3.item_option_b_en AS item_option_b_en_b15i3, xv3.item_option_b_ur AS item_option_b_ur_b15i3, xv3.item_option_c_en AS item_option_c_en_b15i3, xv3.item_option_c_ur AS item_option_c_ur_b15i3, xv3.item_option_d_en AS item_option_d_en_b15i3, xv3.item_option_d_ur AS item_option_d_ur_b15i3, i4.item_id AS item_id_b15i4,xv4.item_option_layout AS item_option_layout_b15i4, xv4.item_stem_en AS item_stem_en_b15i4, xv4.item_stem_ur AS item_stem_ur_b15i4, xv4.item_option_a_en AS item_option_a_en_b15i4, xv4.item_option_a_ur AS item_option_a_ur_b15i4, xv4.item_option_b_en AS item_option_b_en_b15i4, xv4.item_option_b_ur AS item_option_b_ur_b15i4, xv4.item_option_c_en AS item_option_c_en_b15i4, xv4.item_option_c_ur AS item_option_c_ur_b15i4, xv4.item_option_d_en AS item_option_d_en_b15i4, xv4.item_option_d_ur AS item_option_d_ur_b15i4,
//16
xvi1.item_id AS item_id_b16i1,xvi1.item_option_layout AS item_option_layout_b16i1, xvi1.item_stem_en AS item_stem_en_b16i1, xvi1.item_stem_ur AS item_stem_ur_b16i1, xvi1.item_option_a_en AS item_option_a_en_b16i1, xvi1.item_option_a_ur AS item_option_a_ur_b16i1, xvi1.item_option_b_en AS item_option_b_en_b16i1, xvi1.item_option_b_ur AS item_option_b_ur_b16i1, xvi1.item_option_c_en AS item_option_c_en_b16i1, xvi1.item_option_c_ur AS item_option_c_ur_b16i1, xvi1.item_option_d_en AS item_option_d_en_b16i1, xvi1.item_option_d_ur AS item_option_d_ur_b16i1, xvi2.item_id AS item_id_b16i2,xvi2.item_option_layout AS item_option_layout_b16i2, xvi2.item_stem_en AS item_stem_en_b16i2, xvi2.item_stem_ur AS item_stem_ur_b16i2, xvi2.item_option_a_en AS item_option_a_en_b16i2, xvi2.item_option_a_ur AS item_option_a_ur_b16i2, xvi2.item_option_b_en AS item_option_b_en_b16i2, xvi2.item_option_b_ur AS item_option_b_ur_b16i2, xvi2.item_option_c_en AS item_option_c_en_b16i2, xvi2.item_option_c_ur AS item_option_c_ur_b16i2, xvi2.item_option_d_en AS item_option_d_en_b16i2, xvi2.item_option_d_ur AS item_option_d_ur_b16i2, xvi3.item_id AS item_id_b16i3,xvi3.item_option_layout AS item_option_layout_b16i3, xvi3.item_stem_en AS item_stem_en_b16i3, xvi3.item_stem_ur AS item_stem_ur_b16i3, xvi3.item_option_a_en AS item_option_a_en_b16i3, xvi3.item_option_a_ur AS item_option_a_ur_b16i3, xvi3.item_option_b_en AS item_option_b_en_b16i3, xvi3.item_option_b_ur AS item_option_b_ur_b16i3, xvi3.item_option_c_en AS item_option_c_en_b16i3, xvi3.item_option_c_ur AS item_option_c_ur_b16i3, xvi3.item_option_d_en AS item_option_d_en_b16i3, xvi3.item_option_d_ur AS item_option_d_ur_b16i3, xvi4.item_id AS item_id_b16i4,xvi4.item_option_layout AS item_option_layout_b16i4, xvi4.item_stem_en AS item_stem_en_b16i4, xvi4.item_stem_ur AS item_stem_ur_b16i4, xvi4.item_option_a_en AS item_option_a_en_b16i4, xvi4.item_option_a_ur AS item_option_a_ur_b16i4, xvi4.item_option_b_en AS item_option_b_en_b16i4, xvi4.item_option_b_ur AS item_option_b_ur_b16i4, xvi4.item_option_c_en AS item_option_c_en_b16i4, xvi4.item_option_c_ur AS item_option_c_ur_b16i4, xvi4.item_option_d_en AS item_option_d_en_b16i4, xvi4.item_option_d_ur AS item_option_d_ur_b16i4

=============================